publiclab/spectral-workbench

app/assets/javascripts/graphing/importData.js
app/controllers/spectrums_controller.rb
app/controllers/tags_controller.rb
app/models/spectrum.rb
app/models/tag.rb
test/functional/tags_controller_test.rb
test/unit/spectrum_test.rb
test/unit/tag_test.rb

range: tags and powertags in general, tag management and tests

---

app/assets/javascripts/spectralworkbench/SpectralWorkbench.Graph.js
app/assets/stylesheets/graph.css
app/assets/stylesheets/style.css
app/models/spectrum.rb
app/views/embed/spectrum.html.erb
app/views/graph/_body.html.erb
app/views/spectrums/_tools.html.erb
app/views/spectrums/show2.html.erb

primitive zooming, image resizing, tooltip fixes, tools area redesign, fixes for hovers

latest D3 graphing work

---

db/migrate/20150903140344_add_index_likes_count.rb
db/schema.rb

to address slow load times in some pages as documented in https://github.com/publiclab/spectral-workbench/issues/190 by @icarito

added index to spectrums.like_count and .created_at

---

README.md
app/controllers/application_controller.rb
config/database.yml.cloud9
install_cloud9.sh
lib/tasks/cloud9.rake

Easy, 1-line setup script to get code running on https://c9.io
Needs rebasing on top of active 2.0 work, but it's all here.

Cloud9 initialization setup

---

app/assets/javascripts/spectralworkbench/SpectralWorkbench.Tag.js
spec/javascripts/fixtures/graph.html
spec/javascripts/tag_spec.js
spec/javascripts/ui_spec.js

as near a complete Jasmine test suite -- 71 tests -- as I care to achieve at this juncture in my life; close #143

71 passing tests in Jasmine

---

app/assets/javascripts/spectralworkbench/SpectralWorkbench.UI.ToolPaneTypes.js
app/controllers/spectrums_controller.rb
test/functional/spectrums_controller_test.rb

in publiclab/spectral-workbench#217

attempted optimization of spectrum/choose

---

app/models/spectrum.rb

resolved Change Rejected error on capture

---

app/controllers/sets_controller.rb
app/views/graph/_spectra.html.erb

tests passing; relatively urgent as sets pages don't list spectra, or are erroring

fix for sets page display

---

app/controllers/sets_controller.rb

additional sql fix for sets page

---

app/assets/javascripts/spectralworkbench/SpectralWorkbench.API.Operations.js
app/assets/javascripts/spectralworkbench/SpectralWorkbench.PowerTag.js
app/assets/javascripts/spectralworkbench/SpectralWorkbench.Spectrum.js
app/assets/javascripts/spectralworkbench/SpectralWorkbench.Tag.js
app/assets/javascripts/spectralworkbench/SpectralWorkbench.UI.SpectraPane.js
app/assets/javascripts/spectralworkbench/SpectralWorkbench.UI.ToolPane.js
app/assets/javascripts/spectralworkbench/SpectralWorkbench.UI.ToolPaneTypes.js
app/controllers/sets_controller.rb
app/controllers/spectrums_controller.rb
app/controllers/tags_controller.rb
app/models/spectra_set.rb
app/views/layouts/_header.html.erb
app/views/spectrums/new.html.erb
app/views/tags/show.html.erb
public/404.html
public/422.html
public/500.html
spec/javascripts/graph_spec.js
spec/javascripts/operation_spec.js
spec/javascripts/spectrum_spec.js
spec/javascripts/tag_spec.js
test/fixtures/spectra_sets.yml
test/functional/sets_controller_test.rb
test/functional/tags_controller_test.rb
test/unit/spectra_set_test.rb

incomplete; collection of small fixes and upgrades following 2.0.0 release

collection of fixes and upgrades following 2.0.5 release

---

app/assets/javascripts/spectralworkbench/SpectralWorkbench.API.Operations.js
app/controllers/tags_controller.rb

long-running tag query fix, typo correction for calibration: tag

---

app/controllers/tags_controller.rb
app/views/tags/show.html.erb
test/functional/tags_controller_test.rb

stripped tag results graph to optimize sql
tests passing

2.0.8; priority sql optimization

---

app/assets/javascripts/spectralworkbench/SpectralWorkbench.PowerTag.js

snapshot name parsing fix; fixes #314 and possibly related to #309

---

app/assets/javascripts/capture.js
app/controllers/capture_controller.rb
app/controllers/spectrums_controller.rb
app/models/spectrum.rb
app/models/user.rb
app/views/capture/_calibrations.html.erb
app/views/macros/_spectra.html.erb
app/views/users/dashboard.html.erb

Small followup fix; tests passing. Will wait for any additional changes to publish this.

2.1.6 - assorted fixes and updated defaults

---

app/controllers/spectrums_controller.rb
app/models/spectrum.rb
app/views/spectrums/_new_image.html.erb
app/views/spectrums/new.html.erb
app/views/spectrums/show2.html.erb
test/functional/spectrums_controller_test.rb

experimental JSON upload

---

app/controllers/spectrums_controller.rb
app/models/spectrum.rb
app/views/layouts/application.html.erb
app/views/macros/_scripting.html.erb
app/views/spectrums/_new_image.html.erb
app/views/spectrums/new.html.erb
app/views/spectrums/show2.html.erb
bower.json
test/functional/spectrums_controller_test.rb

Rebased on top of #352
Makes a JS editor window instead of a console on spectrum pages.

Macro editor

---

app/assets/javascripts/upload.js
app/controllers/application_controller.rb
app/controllers/spectrums_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/sets/_spectra.html.erb
app/views/spectrums/_list.html.erb
app/views/spectrums/_new_image.html.erb
app/views/spectrums/new.html.erb
app/views/users/dashboard.html.erb
app/views/users/show.html.erb
test/functional/spectrums_controller_test.rb
test/unit/user_test.rb

spectrum upload via API token authentication, CSV upload

---

app/views/spectrums/show2.html.erb
bower.json

Tooltip fixes

---

app/assets/stylesheets/graph.css

overflow:hidden for spectrum image

---

app/controllers/spectrums_controller.rb

image upload fix

---

app/assets/javascripts/upload.js
bower.json

enabling TSV upload via new feature of SpectralWorkbench.js

---

bower.json

tsv improvements via bower.json

---

app/views/spectrums/index.html.erb

dash link fix

---

app/views/graph/_tools.html.erb
app/views/sets/show.html.erb

@icarito - just caught this small bug, but I can wait until your PR is merged before adding this if you prefer?

edit links for sets fixed

---

.travis.yml
lib/tasks/test_all.rake

Missed this in last pull request.
Thanks!

Initialize database before server side tests.

---

README.md

build passing badge for travis ci

---

Gemfile
Gemfile.lock

This seems to have changed yesterday upstream causing tests to fail.
Thanks!

Pin tzinfo to = 0.3.49

---

Gemfile
Gemfile.lock
README.md
app/assets/javascripts/upload.js
app/controllers/application_controller.rb
app/controllers/spectrums_controller.rb
app/models/spectrum.rb
test/functional/spectrums_controller_test.rb
test/unit/spectrum_test.rb
test/unit/user_test.rb

revised JSON api and tests

---

Dockerfile

This is what was causing issues when a dependency got a newer version, caught it finally.
Thanks!

Fix container not taking into consideration Gemfile.lock

---

install_cloud9.sh

Thanks!
Hi, thanks for spectral workbench!
Just trying to get set up to contribute, and ran into some issues with the cloud9 install script. This pull request is a fix for those install issues.
I have a few failing tests on cloud9, but as I haven't changed any application code, I suspect they aren't related to this pull request.
The script failed to install imagemagick and friends, but still exited
successfully and told me the application was running. My install was also
missing bower, which the install script assumes is already installed. This
commit fixes the …

Update cloud9 install script

---

app/views/spectrums/index.html.erb
app/views/users/dashboard.html.erb

Link updates

---

app/views/users/dashboard.html.erb

Update dashboard.html.erb to add questions tag link

---

app/models/user.rb

query optimization for user calibrations

---

README.md

Just a small tweak for linking to the actual tests.

Tweak travis link to tests

---

app/views/spectrums/index.html.erb

Deploying Update index.html.erb (#409)

---

README.md

Typographical error

---

app/views/sessions/login.html.erb

Moved Remember me

---

app/controllers/sessions_controller.rb
app/views/sessions/_login.html.erb
app/views/sessions/login.html.erb

(don't merge yet) Cross Domain Session Management at SWB

---

app/controllers/tags_controller.rb

Addressing #444 
Next 
https://github.com/publiclab/spectral-workbench/blob/03b7b320fdef8d64afde253c76dd1a8e5736cbb2/app/controllers/sets_controller.rb#L15-L46

Optimization, needs testing in console

---

db/migrate/20190513143943_add_snapshots_indices.rb
db/schema.rb

snapshot index on spectrum_id

---

app/assets/stylesheets/style.css
app/views/layouts/application.html.erb

#issue 472 RESOLVED

---

app/controllers/spectrums_controller.rb
test/functional/spectrums_controller_test.rb

Fix image rotation on upload

---

.travis.yml

Parallelize test runner

---

test/functional/sets_controller_test.rb
test/functional/spectrums_controller_test.rb

Add tests for sets and spectrums controller

---

.gitignore
Gemfile
Gemfile.lock
test/test_helper.rb

Includes Simplecov and codecov

---

test/fixtures/comments.yml
test/fixtures/tags.yml

Fix test fixtures

---

app/controllers/comments_controller.rb
test/functional/comments_controller_test.rb
test/unit/comment_test.rb

Coverage after merge= 70.06%
Thanks!

Add comments tests

---

app/controllers/spectrums_controller.rb
app/models/spectrum.rb
app/models/user.rb
test/fixtures/spectra_sets.yml
test/functional/likes_controller_test.rb
test/functional/spectrums_controller_test.rb
test/unit/spectrum_test.rb
test/unit/user_test.rb

Coverage after merge: 74.59%
Thanks!

Add more tests and fix syntax

---

README.md
app/controllers/comments_controller.rb
app/controllers/users_controller.rb
test/functional/comments_controller_test.rb
test/functional/sessions_controller_test.rb
test/functional/users_controller_test.rb
test/unit/comment_test.rb

Increase test coverage percentage

---

app/controllers/capture_controller.rb
test/functional/capture_controller_test.rb
test/functional/comments_controller_test.rb
test/unit/spectra_set_test.rb
test/unit/spectrum_test.rb

Coverage after merge: 79.19%
Thanks!

More tests and syntax changes

---

app/controllers/sets_controller.rb
app/controllers/spectrums_controller.rb
test/controllers/spectrums_controller_test.rb

Fixed bug where comments on sets were not being deleted
Fixed bug where spectrum could not be edited
Fixed corresponding test
Thanks!

Fix comment bug and spectrum update

---

.gitpod.dockerfile
.gitpod.yml
Gemfile
Gemfile.lock
README.md
config/database.yml.gitpod

Available at: https://fac31da2-a42d-4cdb-9c3b-c7c41682cda1.ws-us02.gitpod.io/#/workspace/spectral-workbench
Thanks!

Setting up GitPod

---

Dockerfile

This allowed staging to build again. 
Thanks!

Replace reference to jessie with stretch

---

Gemfile.lock
docker-compose.yml

Remove locked reference to outdated Gem

---

app/controllers/spectrums_controller.rb

addressing https://github.com/steviepubliclab/web/issues/333
Thanks!

Re-add limits from #499 for front page

---

app/models/user.rb

fix tags query to resolve /upload 404/500 error

---

.gitignore

Fixes #659 Updated .gitignore to remove the node_modules folder
Thanks!

Updated .gitignore to remove node_modules folder

---

package.json
yarn.lock

Attempt at narrower version of #658 for just SWB.js upgrade

Upgrade to SWB.js v0.2.0

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/views/layouts/application.html.erb
app/views/layouts/embed.html.erb
package.json
public/404.html
public/422.html
public/500.html
yarn.lock

Updating dependencies, checking for breaking changes

---

script/start.sh

bundle exec rake assets:precompile

---

Gemfile.lock

Trying fix for gitpod workflow 

---

Gemfile.lock
app/assets/config/manifest.js

Otherwise stable won't build
Thanks!

Use the same version as available in container

---

app/views/users/dashboard.html.erb

dashboard.html.erb: Make sidebar consistent with the header

---

README.md

With the latest changes, the dependencies in the `README.md` file were not updated.
Thanks!

Fixed dependency versions in docs

---

app/controllers/match_controller.rb
config/routes.rb

fixes https://github.com/publiclab/spectral-workbench/issues/727
needs GitPod test
test in https://spectralworkbench.org/match/search/226540?toolPane=true once complete

add /match/search/226540 back to routes

---

test/integration/routes_test.rb

Add routes test file with spectrums/choose route test
Thanks!

add routes test file

---

test/integration/routes_test.rb

Add routes test for match/search/:id #780

---

test/integration/routes_test.rb

Fixes #742
* [] tests pass -- `rake test`
Thanks!

Add routes test for sets/new/:id

---

test/integration/routes_test.rb

Add routes test for spectrums/destroy/:id #783
Thanks!

Added routes test for spectrums/destroy

---

test/integration/routes_test.rb

I added the required lines to the code.
Thanks!

added the spectrum update id to the file

---

test/integration/routes_test.rb

Please review the changes
Thanks!

Added routes test for match/:id #779

---

test/integration/routes_test.rb

fixes #811 
Hii,
This is my first commit,
I have added the lines
+  test "test get request for match livesearch" do
+    assert_routing({ path: '/match/livesearch', method: 'get' }, {controller: 'match', action: 'livesearch' })
+  end
to routes_test.rb
Thanks!

Update to routes_test.rb

---

test/integration/routes_test.rb

added test coverage for spectrums

---

test/integration/routes_test.rb

Add routes test for match/get_conditions

---

test/integration/routes_test.rb

chore: added routes test for 'match/search'

---

test/integration/routes_test.rb

Added routes test for spectrums/fork/:id

---

test/integration/routes_test.rb

Fixes #(854)
* [ x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ x] pull request are descriptively named
* [ x] if possible, multiple commits squashed if they're smaller changes
Thanks!

Fixes issue 854 by adding a test for post requests for sets add

---

test/integration/routes_test.rb

Added routes test for sets/show2 (fixes #855)

---

test/integration/routes_test.rb

Added tests for path : '/spectrums/plots_rss' 

---

test/integration/routes_test.rb

Routes test added for spectrums/compare_search

---

test/integration/routes_test.rb

Adding routes test for spectrums/all

---

test/integration/routes_test.rb

Adds test for path: 'spectrums/show2'

---

app/assets/javascripts/capture.js
app/controllers/spectrums_controller.rb
app/views/capture/_newsave.html.erb
app/views/capture/_save.html.erb
app/views/capture/index2.html.erb
app/views/spectrums/new-errors.html.erb
app/views/spectrums/new.html.erb

Port Geocode tool back into new Capture interface,

---

app/views/capture/index2.html.erb

Reproduce detection of fluorescent lights from legacy capture interface into new capture interface

---

test/integration/routes_test.rb

Issue #862, required changes are done
Thanks!
Fixes #862

Routes test for spectrums/set_search added

---

test/integration/routes_test.rb

Add routes test for sets/calibrated

---

app/assets/javascripts/basics.js
app/views/layouts/application.html.erb

GA4 tags update

---

Dockerfile

try to upgrade to node 16
